//------------------------------------------------------------------------------
// <auto-generated>
//     Ce fichier est généré par XmlnsDefinitions.tt — NE PAS L'ÉDITER À LA MAIN.
//     Pour régénérer : clic droit sur XmlnsDefinitions.tt > "Exécuter l'outil
//     personnalisé" (Run Custom Tool), ou enregistrez simplement le .tt.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Windows.Markup;
using System.Windows;

[assembly: ThemeInfo(
    ResourceDictionaryLocation.None,            //where theme specific resource dictionaries are located
                                                //(used if a resource is not found in the page,
                                                // or application resource dictionaries)
    ResourceDictionaryLocation.SourceAssembly   //where the generic resource dictionary is located
                                                //(used if a resource is not found in the page,
                                                // app, or any theme specific resource dictionaries)
)]

[assembly: XmlnsDefinition("http://custom.mvvm.wpf.ui.com/dotnet/wpf/converters", "CustomMvvmWpf.UI.Converters")]
[assembly: XmlnsDefinition("http://schemas.microsoft.com/winfx/2006/xaml/presentation", "CustomMvvmWpf.UI.Behaviors")]
[assembly: XmlnsDefinition("http://schemas.microsoft.com/winfx/2006/xaml/presentation", "CustomMvvmWpf.UI.Controls.Layouts")]
[assembly: XmlnsDefinition("http://schemas.microsoft.com/winfx/2006/xaml/presentation", "CustomMvvmWpf.UI.ViewModels")]
[assembly: XmlnsDefinition("http://schemas.microsoft.com/winfx/2006/xaml/presentation", "CustomMvvmWpf.UI.Views")]
